### ISSUE TITLE
Separate the indexer from the crawler?

### ISSUE THREAD

**Issue by justinccdev** [buzzbangorg/bsbang-crawler-ng#15]
I think what we could do now is separate the indexing code from the crawler and put the indexer into a separate git project.  That way, the indexer can work on data crawled by NG crawler, gocrawlit or something else. There could also be multiple indexers for different purposes, like putting data into Solr, ES or the semantically aware BioSolr. @innovationchef @ricardoaat 

Depending on what progress has been made already, what we could to start is rip out the brain dead 'indexing' from the old buzzbang crawler (tracing through from [`bsbang-index.py`](https://github.com/buzzbangorg/bsbang-crawler/blob/dev/bsbang-index.py)) and adapting it to read from MongoDB (currently Ankit's format, but soon the common format).  Then improve that to be not so brain dead, or use it as a base for a better indexer.

**Comment by innovationchef** [comment]
Done! Link to new basbang-indexer repo - https://github.com/buzzbangorg/bsbang-indexer
