### ISSUE TITLE
Allow user configuration outside of the source tree

### ISSUE THREAD

**Issue by justinccdev** [buzzbangorg/bsbang-crawler-ng#3]
At the moment, if a user wants to edit config they have to do it in `settings.py`, which is under source control.  This is a pain for someone testing.  There is also a danger that they may put sensitive credentials there in the future.

Can we do user config (e.g. mongodb settings) in a place outside of source control?  One possible approach is to supply only `settings.py.example` and require the user to copy this to `settings.py` during installation.

**Comment by innovationchef** [comment]
Resolved  - [Commit](https://github.com/buzzbangorg/bsbang-crawler-ng/commit/7905c917d7f58c40c33b6a681e026e5d4d360824)
