### ISSUE TITLE
Avoid rescraping pages already present in MongoDB?

### ISSUE THREAD

**Issue by justinccdev** [buzzbangorg/bsbang-crawler-ng#6]
The existing crawler has code that avoids rescraping an URL if we already have that data in SQLite.  This was for performance reasons, and so that the scraper could be arbitrarily stopped and started without starting from the beginning all the time.

Is it possible to do this with Scrapy?  For now, a very simple approach that never scrapes if we already have the data is feasible, but in the future we will want configurable strategies (e.g. only scrape if data is older than x days).  Perhaps Frontera has some logic for this already, though don't know how easy it would be to reuse that.

Is it necessary?  Although in a production setting with powerful machines I suppose you could argue that rescraping doesn't take that long, this time will multiply when the sites increase.  And during development, rescraping big sites all the time for test purposes is not really feasible.

**Comment by justinccdev** [comment]
It also might be annoying to the scrapees if we are constantly scraping them for test purposes

**Comment by justinccdev** [comment]
This probably requires us to store the URL that the Bioschemas came from in Mongo.  This is what the older scraper does.

**Comment by innovationchef** [comment]
The same can be implemented here also (will have to look how). I have another concern - Is the data of each sample updated? The ebi biosamples sitemap gives other information like last modified date, change frequency, priority etc. Is this information useful? If the data of each sample is updated often, then we need to keep track of URL as well as this date. Also, the sitemap of ebi biosamples contains lastmod, changefreq and priority nodes, but [these are optional](https://www.sitemaps.org/protocol.html) and may not be a part of some other sitemap that users may want to crawl in future. So, should I go with only the URLs?

To answer your 2nd question - I can't say for sure if avoiding rescraping pages already in MongoDB is a nice idea or not. Say we implemented this, then, we will first check if a URL is already scraped or not (by querying the DB) and then take the decision to scrape it. For 1 million URLs, it would mean 1 million sequential queries to DB and web. The process of querying the DB will pause the scrapy engine too (or could it be done in a separate process???). I need your thoughts on this as well. 

Again, if this is implemented, we could at least give the user an optional argument to tell our code if this is a fresh crawl. In case of fresh crawls, we will remove the MongoDB querying part.

**Comment by innovationchef** [comment]
I am not adding another field in the mongodb collection for URLs. The json-ld that we are extraction already contains the sample URL, so we can simply query that to check if a sample is already in the db.

**Comment by innovationchef** [comment]
There is one more thing, the sitemap enlists all the link with HTTP protocol. However, the sample pages don't open with this and rather gets redirected to the HTTPS protocol. So why isn't the sitemap listing the URL with HTTPS?

Because of this behaviour, I have to spend extra computation for pushing short URLs in the DB without HTTP and the use regex expression to check if it is already present in the DB.

**Comment by justinccdev** [comment]
* If we are avoiding rescraping, don't we only need the query to the database rather than the web as well?  1m sequential is not actually that much and could anyway be more efficiently fetched as batches of URLs if this proved to be an issue.
* I would just go with the URLs on the sitemap for now.  But perhaps that would be useful in the future to detect freshness of data.
* If I were to guess, I would say that it's probably just that they haven't updated the code generating the sitemap to use https.  But I will ask one of the project developers when I have an opportunity.

**Comment by innovationchef** [comment]
- I implemented the feature and it is indeed working faster.
 - Yes, I think I should not worry about this now. We will take that later.
Closing this issue.
